### ISSUE TITLE
Missing maven 

### ISSUE THREAD

**Issue by adamkowalewski** [GrzegorzKossowski/Java#3]
Projekt wykonany w technologi Java który nie jest budowany przy użyciu Maven bądź Gradle to anty-pattern. 
IMHO: Pojedyncze projekty powinny być zorganizowane jako moduły 
np. `pom.xml` jako parent pom repozytorium z `dependency management`, każdy projekt jako moduł

**Comment by GrzegorzKossowski** [comment]
To oznacza, że:
a) muszę douczyć się mavena
b) a co w sytuacji, kiedy różne projekty korzystają z odmiennych technologii? Np. FX, albo Spring, albo co-tam-jeszcze... Wtedy pom będzie ogromniasty... (jeśli ma być jeden wspólny).

**Comment by adamkowalewski** [comment]
a) koniecznie 
b) Parent pom jest odpowiedzialny za dependency Management np:
https://github.com/wildfly/wildfly/blob/master/pom.xml
https://github.com/OtwartaPlatformaWyborcza/opw-pre
